// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ABreadcrumb: typeof import('ant-design-vue/es')['Breadcrumb']
    BasicHelp: typeof import('./src/components/Basic/src/BasicHelp.vue')['default']
    BasicMenu: typeof import('./src/components/Menu/src/BasicMenu.vue')['default']
    BasicMenuItem: typeof import('./src/components/Menu/src/components/BasicMenuItem.vue')['default']
    BasicModal: typeof import('./src/components/Modal/src/BasicModal.vue')['default']
    BasicSubMenuItem: typeof import('./src/components/Menu/src/components/BasicSubMenuItem.vue')['default']
    BasicTitle: typeof import('./src/components/Basic/src/BasicTitle.vue')['default']
    CollapseContainer: typeof import('./src/components/Container/src/collapse/CollapseContainer.vue')['default']
    CollapseHeader: typeof import('./src/components/Container/src/collapse/CollapseHeader.vue')['default']
    CountButton: typeof import('./src/components/CountDown/src/CountButton.vue')['default']
    CountDownInput: typeof import('./src/components/CountDown/src/CountDownInput.vue')['default']
    CountTo: typeof import('./src/components/CountTo/src/CountTo.vue')['default']
    Description: typeof import('./src/components/Description/src/Description.vue')['default']
    Dropdown: typeof import('./src/components/Dropdown/src/Dropdown.vue')['default']
    Editor: typeof import('./src/components/Tinymce/src/Editor.vue')['default']
    Icon: typeof import('./src/components/Icon/src/Icon.vue')['default']
    IFrame: typeof import('./src/components/IFrame/src/IFrame.vue')['default']
    ImgUpload: typeof import('./src/components/Tinymce/src/ImgUpload.vue')['default']
    Loading: typeof import('./src/components/Loading/src/Loading.vue')['default']
    LocalePicker: typeof import('./src/components/Application/src/LocalePicker.vue')['default']
    Logo: typeof import('./src/components/Application/src/Logo.vue')['default']
    Markdown: typeof import('./src/components/Markdown/src/Markdown.vue')['default']
    Menu: typeof import('./src/components/SimpleMenu/src/components/Menu.vue')['default']
    MenuItem: typeof import('./src/components/SimpleMenu/src/components/MenuItem.vue')['default']
    MenuItemContent: typeof import('./src/components/Menu/src/components/MenuItemContent.vue')['default']
    Modal: typeof import('./src/components/Modal/src/components/Modal.vue')['default']
    ModalClose: typeof import('./src/components/Modal/src/components/ModalClose.vue')['default']
    ModalHeader: typeof import('./src/components/Modal/src/components/ModalHeader.vue')['default']
    ModalWrapper: typeof import('./src/components/Modal/src/components/ModalWrapper.vue')['default']
    PageFooter: typeof import('./src/components/Page/src/PageFooter.vue')['default']
    PageWrapper: typeof import('./src/components/Page/src/PageWrapper.vue')['default']
    Provider: typeof import('./src/components/Application/src/Provider/index.vue')['default']
    QrCode: typeof import('./src/components/QrCode/src/QrCode.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Scrollbar: typeof import('./src/components/Scrollbar/src/Scrollbar.vue')['default']
    ScrollContainer: typeof import('./src/components/Container/src/ScrollContainer.vue')['default']
    SimpleMenu: typeof import('./src/components/SimpleMenu/src/SimpleMenu.vue')['default']
    SimpleSubMenu: typeof import('./src/components/SimpleMenu/src/SimpleSubMenu.vue')['default']
    Src: typeof import('./src/components/Dropdown/src/index.vue')['default']
    SubMenuItem: typeof import('./src/components/SimpleMenu/src/components/SubMenuItem.vue')['default']
    SvgIcon: typeof import('./src/components/Icon/src/SvgIcon.vue')['default']
  }
}

export {}
